#!/bin/sh
i3lock -i /home/kannab/.dotfiles/wallpaper/neon_resize.png \
    --insidecolor=373445ff --ringcolor=ffffffff --line-uses-inside \
    --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
    --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
    --ringvercolor=ffffffff --ringwrongcolor=ffffffff  \
    --indpos="x+86:y+1003" \
    --radius=14 --veriftext="" --wrongtext="" --noinputtext=""
xkb-switch -s us
